all: a
	./a.out < Teste_1.txt
	@printf "\n\n"
	./a.out < Teste_2.txt
	@printf "\n\n"
	./a.out < Teste_3.txt
	@printf "\n\n"
	./a.out < Teste_4.txt
	@printf "\n\n"
	./a.out < Teste_5.txt
	@printf "\n\n"
	./a.out < Teste_6.txt
	@printf "\n\n"
	./a.out < Teste_7.txt
	@printf "\n\n"
	./a.out < Teste_8.txt
	@printf "\n\n"
	./a.out < Teste_9.txt
	@printf "\n\n"
	./a.out < Teste_10.txt
	@printf "\n\n"
	./a.out < Teste_11.txt
	@printf "\n\n"
	./a.out < Teste_12.txt
	@printf "\n\n"
	./a.out < Teste_13.txt
	@printf "\n\n"
	./a.out < Teste_14.txt
	@printf "\n\n"
	./a.out < Teste_15.txt
	@printf "\n\n"

a: main.cc
	lex tradutor.l
	g++ -Wall -std=c++17 main.cc -lfl

clean:
	rm a